name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-20.04
    steps:
      - name: echo a string
        run: echo "Hello Rejohn"
      - name: multiline script
        run: |
          node -v
          npm -v